# Generated by Django 5.0.6 on 2024-05-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique_for_date='deadline', verbose_name='Имя задачи.')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Blocked', 'Blocked'), ('Done', 'Done'), ('No status', 'No status')], default='No status', max_length=20, verbose_name='Статус выполнения')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дата дедлайна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задания')),
                ('categories', models.ManyToManyField(to='my_app.category', verbose_name='tasks')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название подзадачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание подзадачи')),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Blocked', 'Blocked'), ('Done', 'Done'), ('No status', 'No status')], default='No status', max_length=20, verbose_name='Статус выполнения')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дата дедлайна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='my_app.task', verbose_name='Задача')),
            ],
        ),
    ]
